# Generated by Django 4.0.5 on 2022-06-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_movietrailer_delete_movieshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='films/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='movietrailer',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='films.movie', verbose_name='Фильм'),
        ),
    ]
