# Generated by Django 4.0.5 on 2022-06-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_movie_poster_alter_movietrailer_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название фильма')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('year', models.IntegerField(verbose_name='Год выхода фильма')),
                ('raiting_IMDB', models.FloatField(blank=True, null=True, verbose_name='Рейтинг IMDB')),
                ('raiting_KP', models.FloatField(blank=True, null=True, verbose_name='Рейтинг Кинопоиска')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='poster/', verbose_name='Постер фильма')),
                ('budget', models.PositiveIntegerField(verbose_name='Бюджет')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Режиссер')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='producers/', verbose_name='Фото режиссера')),
            ],
            options={
                'verbose_name': 'Режиссер',
                'verbose_name_plural': 'Режиссеры',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movietrailer',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='star',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='url',
        ),
        migrations.AddField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='actors/', verbose_name='Фото актера'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.TextField(verbose_name='Актер'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.TextField(verbose_name='Жанр'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MovieTrailer',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(related_name='film_actors', to='films.actor', verbose_name='актеры'),
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='film_genres', to='films.genre', verbose_name='жанры'),
        ),
        migrations.AddField(
            model_name='film',
            name='producers',
            field=models.ManyToManyField(related_name='film_producers', to='films.producer', verbose_name='режиссеры'),
        ),
    ]
