# Generated by Django 4.0.5 on 2022-06-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_film_producer_remove_movie_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Актер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Режиссер'),
        ),
    ]
